rem "Starting sc2 bot . . ."
rem python "MutaliskBrood.py"
rem python "HydraliskBrood.py"
python "ZealotTribe.py"
rem python "VoidRaySpam.py"
rem python "CarrierSpam.py"
rem python "ZealotRush.py"
rem python "HiveMind.py"
rem python "WarpInArmy.py"
rem python "bot_vs_bot.py"
rem python "Zerglings.py"
pause